### PR TITLE
Updated Command line help to reflect all possible TestResult-Formats

### PR DESCRIPTION
**Pull request by magicmonty**

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks for this contribution too. There are some failing unit test ... and I still haven't fixed the build process so the CI build doesn't notice. Could you fix the failing unit tests please? I'll do my best to get the build process fixed today.

**Comment by dirkrombauts** [comment]
BTW I fixed the build process.

Incidentally, if you want to run the same build on your machine that's running on the server: open a command window in the root directory of the repository and start build.bat

**Comment by magicmonty** [comment]
Cool, I fixed the failing tests.

**Comment by dirkrombauts** [comment]
Thanks!

**Comment by dirkrombauts** [comment]
Released as version [2.6.2](https://github.com/picklesdoc/pickles/releases/tag/v2.6.2)

**Pull request merged**
