### PR TITLE
Fixed ExcludeTags Typo In MSBuild targets

### PR DESCRIPTION
**Pull request by nachereshata**
Fixed Typo

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thank you for your contribution. I added an entry to the change log.

**Comment by dirkrombauts** [comment]
Resolves #486

**Comment by nachereshata** [comment]
Than YOU for Pickles :)

**Comment by dirkrombauts** [comment]
Released in version [2.17.0](https://github.com/picklesdoc/pickles/releases/tag/v2.17.0).

**Pull request merged**
