### PR TITLE
#357 Sorts features descending by name for Word.

### LINKED ISSUE #357: Sorting features in output file (MS Word)
I'm trying to sort my features in output word file by the name of feature-files.

I have 2 files:

[01 - First step part one.feature.txt](https://github.com/picklesdoc/pickles/files/369213/01.-.First.step.part.one.feature.txt)
[02 - First step part two.feature.txt](https://github.com/picklesdoc/pickles/files/369214/02.-.First.step.part.two.feature.txt)

And when I convert it into "docx", i see:
contents

I expected to see the feature "First step part one" in the beginning of the list-content

But when I rename a head of the first file to 
```
Feature: First Z-step part one
```
then I see correct word-file:
contents-right

### PR DESCRIPTION
**Pull request by lars-erik**
This fixes #357, but it's a naive hack. Don't know whether it's relevant for other builders or if the order is random. In any case, the word implementation seems to be reversing somewhere, so sorting by descending before word re-sorts solves it for now.

Thanks a lot for a great tool! :)

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks. The code looks good. However, I am following a test-first policy on Pickles, so in order for me to merge this pull request, there need to be some unit tests. Do you think you could add those?

**Comment by lars-erik** [comment]
I didn't find that the code have coverage as-is. I'll gladly add the test if I know which fixtures. 😊

Vennlig hilsen

Lars-Erik Aabech
Faglig leder utvikling
MarkedsPartner AS
www.markedspartner.no
+47 920 30 537
________________________________

**Comment by dirkrombauts** [comment]
Hmm you're right ... the word output formatter doesn't have unit tests. Forget what I said in this instance :-)

**Comment by lars-erik** [comment]
I’ll look for a fixture for the results-file parsing. Guess that’s present. I just fell into bad habits after the first PR. ;)

Lars-Erik Aabech
Faglig leder utvikling
MarkedsPartner AS
www.markedspartner.no<http://www.markedspartner.no>
+47 920 30 537

**Comment by dirkrombauts** [comment]
@lars-erik I wanted to merge this PR but there's a conflict. Could you take a look at that please?

**Comment by lars-erik** [comment]
You removed NGenerics a couple of days after I made the change. Have to do it over since I wrote the sorting for the NGenerics classes. I'll see about it while looking at the plugin structure. Shouldn't be too difficult, but the current code is rather useless. I also discovered it affects Excel files too, so it should probably go into a class further out or further up the hierarchy.

**Comment by dirkrombauts** [comment]
Oh dear ... I'm sorry ... while removing the NGenerics classes I did have the nagging feeling that there was something I was overlooking. Now I know what it is.

**Comment by dirkrombauts** [comment]
In my opinion, fixing this is more important than a plugin concept for output formatters.

**Comment by lars-erik** [comment]
I agree.

I’ll see what I can do, but if you’re already fiddling with it, I think it’s just a matter of adding .OrderBy(feature => feature.Name) if you’re using vanilla generic collections now.

**Pull request closed without merging**
