### PR TITLE
Add --enableComments Flag to Command Line - Default to True

### PR DESCRIPTION
**Pull request by ocsurfnut**
A simple change to allow us to turn off comments in output if needed.

### CODE REVIEW

**Comment by dirkrombauts** [comment]
I didn't look at the code yet, so only two quick comments:

1. Please name the parameter "enableComments". The default value of true is good.
2. It's good practice to rebase your develop branch from the picklesdoc develop branch and to then create a feature branch for your work. That will eliminate most of the weird history issues.

**Comment by dirkrombauts** [comment]
And of course: thank you for your continuing contributions!

**Comment by ocsurfnut** [comment]
@dirkrombauts , changed command-line arg to `--enableComments`.  Also rebased and got rid of weird history, thanks!

**Comment by dirkrombauts** [comment]
Glad you got the history sorted out!

I'm taking a training tomorrow, so I probably won't get around to reviewing your PR in detail until Wednesday (central european summer time).

**Comment by dirkrombauts** [comment]
Looks good so far. Would you please also add the option to the three other runners? Thanks!

**Comment by ocsurfnut** [comment]
Just pushed additions to other runners @dirkrombauts

**Comment by dirkrombauts** [comment]
Thanks, I will review it later today (or tomorrow)!

**Comment by dirkrombauts** [comment]
@ocsurfnut thanks for your work. The msbuild and powershell runners look good.

There's a slight problem with the UI runner, though.

When I open the UI, set "Enable Comments" to off, close the UI and open the UI again, then I expect the "Enable Comments" switch to be off. It is turned on.

Could you please look into that? Thanks!

**Comment by ocsurfnut** [comment]
@dirkrombauts , good catch, was setting the backing field `enableComments` instead of using the `EnableComments` property, so the `PropertyChanged` notification wasn't getting fired.  Fixed now.

**Comment by dirkrombauts** [comment]
Thanks! I plan to release this next week - so there's time if you have some more contributions ;-)

**Comment by ocsurfnut** [comment]
Thanks @dirkrombauts!  This is the only other one I'd like to get into the release if possible: https://github.com/picklesdoc/pickles/pull/350

**Comment by dirkrombauts** [comment]
Released in [version 2.7.0](https://github.com/picklesdoc/pickles/releases/tag/v2.7.0)

**Pull request merged**
