### PR TITLE
Add IMarkdownProvider to allow changing the MarkdownProvider used

### PR DESCRIPTION
**Pull request by dstj**
Adding an interface for MakrdownProvider will make it easier to change the Markdown parsing engine used.
(I will use Markdownify)

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thank you, good idea!

**Comment by dirkrombauts** [comment]
Could you send me a link to markdownify? A quick google search did not yield a clear result :-(

**Comment by dstj** [comment]
Ah, it seems I was mistook the our class name for the dependencie's project name... sorry about that.

Strike.V8 is the project name:
https://www.nuget.org/packages/Strike.V8/

It wraps this parser for .NET
https://github.com/chjj/marked/

**Comment by dirkrombauts** [comment]
What are the advantages of this parser/engine over the engine that Pickles is currently using?

**Comment by dstj** [comment]
It's been a while since we changed it (we recently had to update Pickles because of the Powershell issue you fixed), but if I remember correctly, it was formatting issue with github flavored markdown, namely tables. I can check a little later to confirm if anything else we messed up in the html output and can back to you

**Comment by dirkrombauts** [comment]
Could you perhaps make a screenshot of a page rendered with your version of Pickles and of the same page rendered with the official version? Ideally a page that shows off the benefits of Mordownify/Strike.v8/marked

**Comment by dstj** [comment]
Hi Dirk,

Sorry for taking so long... I simply got caught up in my regular work... and forgot ;)

I ran our doc generation process against our custom Strike.V8 version and with the out-of-the-box Pickles version.

The differences are with embedded HTML tags (see image)
embedded-html and with the triple back-tick code blocks (github flavoured markdown).

Our process runs the Pickles output through a "beautifier" to improve the visual. The `<span class="hidden">` were hidden, they are only used for ordering the documentation pages (alphabetically made no sense for us)

But, the code blocks were the biggest pain. 

Strike.V8 output `<pre><code>` block, whereas regular pickles outputs normal `<p>` tags, making it impossible to add custom CSS/highlightjs, etc. to make it pretty. Here's a example:

### Strike-V8 output
```
<p>Simply copy-paste the following content in a <code>proxy.html</code> file beside your "edit project" page:</p>
        <pre>
          <code class="lang-html">&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
  &lt;script type="text/javascript"&gt;
    window.onload = function () { Porthole.WindowProxyDispatcher.start(); };
  &lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;&lt;/body&gt;
&lt;/html&gt;
</code>
```

###  Default Pickles output
```
<p>Simply copy-paste the following content in a <code>proxy.html</code> file beside your "edit project" page:</p>
        <p>```html
&lt;!DOCTYPE html&gt;
&lt;html&gt;</p>
&lt;head&gt;
  &lt;script type="text/javascript"&gt;
    window.onload = function () { Porthole.WindowProxyDispatcher.start(); };
  &lt;/script&gt;
&lt;/head&gt;
<p>&lt;body&gt;&lt;/body&gt;
&lt;/html&gt;
```</p>
```

Hope that helps to understand why we need the other engine.

**Pull request merged**
