### PR TITLE
Added Command-Line Flag --nocomments - Sans Unit Tests

### PR DESCRIPTION
**Pull request by ocsurfnut**
Hey @dirkrombauts , this is my first pass at adding the command-line flag `--nocomments` to disable the new feature in 2.6.0 that shows comments.  If this direction looks good to you, I'll add in some unit tests and finalize.  Thanks!

### CODE REVIEW

**Comment by jamiesmy** [comment]
Thanks @ocsurfnut

**Comment by dirkrombauts** [comment]
Thanks for your contribution! I'm at a conference so I haven't had time to review your PR in detail. I did have a quick look and it looks plausible.

One request though: I like arguments to be positive, so I'd prefer "includecomments" with a default value of true rather than "nocomments" with a default value of false.

**Comment by dirkrombauts** [comment]
@ocsurfnut how are you? Is there anything I can do to help you along with the rest of this story?

**Comment by dirkrombauts** [comment]
@ocsurfnut how are you? In order to keep maintenance overhead of Pickles small, I am going to close this pull request soon. Please feel free to send me a new PR when you get around to completing the feature.

**Comment by ocsurfnut** [comment]
Hi @dirkrombauts , I've been out of town and busy with other projects.  I do plan on circling back to this in the next week or so, but if you need to close this PR, I understand.  

One question, in order to make this use a "positive" flag such as `--includecomments` (or maybe just `--comments`), the default would then become to not show comments, effectively undoing the hard work of @ludwigjossieaux.  Is this acceptable?

**Comment by dirkrombauts** [comment]
I'm closing it now, github makes it really easy to create new PRs.

I like the sound of `--includeComments` rather than `--comments`, and I would give it a default value of `true`.

**Comment by ocsurfnut** [comment]
So usage would be `--includeComments=false` in my case?

**Comment by dirkrombauts** [comment]
If your goal is to NOT show the comments, then yes, that is what you would pass as an argument.

**Pull request closed without merging**
