### PR TITLE
Adding support for syntax highlight to <code>

### PR DESCRIPTION
**Pull request by jboffel**
As you have the support for markdown which let you add <code> HTML tag then it can be nice to have the syntax highlighting for the code to have a better reading of the documentation!

### CODE REVIEW

**Comment by dirkrombauts** [comment]
This is an intriguing idea, but I'm a bit hesitant to include it right away. Could you give me an example where code highlighting would be useful? Thanks!

**Comment by jboffel** [comment]
In my case I'm adding sample of soap API call, aka XML and i enclosed it
with a pre/code through markdown.
And I feel it is more readable with syntax highlights.
But I could also imagine to include in the feature or scenario description
snippet of code in various languages to show how to call our API as well to
help our stakeholder.

Regards

**Comment by dirkrombauts** [comment]
I would prefer to have this as an experimental feature, like the mathematical formulas. Do you think you could adapt your code to follow that pattern?

**Comment by dirkrombauts** [comment]
BTW: this pull request includes the change you already sent me about the unix paths. It's a good Git(Hub) practice to create a new branch for each feature you work on. Don't work directly in the develop branch.
Does that makes sense or did I just talk latin?

**Comment by jboffel** [comment]
Make sense. I'll see what I can do on next week to make it compliant to
your standard.

**Comment by dirkrombauts** [comment]
@jboffel how are you getting along with this?

**Comment by jboffel** [comment]
Sorry right now I got no time to work on this one. I'm not sure when I'll
be able to make it follow your process but maybe from next month...

**Comment by dirkrombauts** [comment]
No worries. However, in order to reduce the maintenance overhead of Pickles, I am going to close this pull request for now. Please continue to work on it at your own pace, and you can always open a new pull request in the future.

**Pull request closed without merging**
