### PR TITLE
WIP: Fix: XUnit failed, if multiple TestResults.xml were used

### PR DESCRIPTION
**Pull request by magicmonty**
If I used multiple SpecFlow projects with XUnit2, then there was a NullReferenceException for the Features of the other Dlls, which lead to an abort of the test generation. Also if an example contained a "*" as input, the generation of the Regex failed

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thank you for your contribution! It is thanks to people like you that I can keep Pickles up to date and relevant.

I try to follow a strict test-first policy, so I would like to have all code changes accompanied by unit tests. The [Contributing.md](https://github.com/picklesdoc/pickles/blob/develop/CONTRIBUTING.md) file explains how to add unit tests for the code about the test result providers.

With regard to your change to the xUnitExampleSignatureBuilder: I think you are working from an old codebase. A couple of days ago I merged a [pull request](https://github.com/picklesdoc/pickles/pull/332) that deals with special characters. Could you verify that you are using the latest code? (I con't verify right know because I'm on a mac without Visual Studio :-( )

Thank you again for your efforts. If you need more information to continue, please let me know!

**Comment by magicmonty** [comment]
Sorry for the missing tests (my bad, will fix that). I will check the version too.

**Comment by dirkrombauts** [comment]
Thanks!

**Comment by magicmonty** [comment]
Added at least the unit tests for the Regular expression in examples case. I currently don't know how to test the other issue.

**Comment by magicmonty** [comment]
Now all other test frameworks are tested also for this issue (except for SpecRun and VSTest, where I cannot derive the name from the example value)

**Comment by dirkrombauts** [comment]
hi, there's something weird going on. The CI build passes, but when I download your changes to my computer it does not compile. The `WhenParsing*REsultsFileWithIndividualResults.cs` files all reference a method in the base class (as it should be) but the base class (`StandardTestSuiteForScenarioOutlines`) does not have that method.

Could you please double-check on your side?

**Comment by dirkrombauts** [comment]
As for testing the NullReference bit when combining multiple specflow projects: I just noticed that there's no tests for that in the test result providers where I fixed that problem in the past. So you don't need to look for a way to test that now. Let's focus on getting the regex stuff tested.

**Comment by magicmonty** [comment]
You are right. It seems, I have forgotten to commit and push this one. Will do it on Monday morning, as I'm on the road today

**Comment by dirkrombauts** [comment]
Thanks. Still, funny that the CI build passes ...

**Comment by magicmonty** [comment]
Found the reason, why the CI build succeeds: The UnitTests for the TestFrameworks were never build nor executed. Added a commit to prove this behaviour

**Comment by magicmonty** [comment]
Unfortunately the AppVeyor Build does not break, when the Build of the Test-Project fails

**Comment by magicmonty** [comment]
Added the missing method, but made it fail, to check, if the CI build breaks now...

**Comment by magicmonty** [comment]
The tests seems not to be run at CI build (should break with the last commit):

<https://ci.appveyor.com/project/dirkrombauts/pickles-715/build/1.0.412>

Anyway, this is not the scope of this PR

**Comment by magicmonty** [comment]
The last push fixes the (supposedly) breaking build

**Comment by dirkrombauts** [comment]
Thanks again for your contribution, and also a lot of thanks for your diagnostic work. I need to fix the build process!
Dankeschön!

PS: I will release a new version of Pickles tomorrow!

**Comment by magicmonty** [comment]
Nice, and Gern geschehen. Keep up the good work.

**Comment by dirkrombauts** [comment]
Released in version [2.6.1](https://github.com/picklesdoc/pickles/releases/tag/v2.6.1).

**Comment by magicmonty** [comment]
Thanks, already in production ;)

**Pull request merged**
