### PR TITLE
Abbreviations displayed incorrectly with spaces between letters

### PR DESCRIPTION
**Pull request by sergeyshushlyapin**

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks for the pull request. My regular expressions are a bit rusty - could you please explain what the change does?

**Comment by sergeyshushlyapin** [comment]
Dirk, thank you for pointing me in the right direction! The best way to explain smth. is to write a unit test ;)  
I created a test which checks that an abbreviation added to the end of a title is parsed correctly. Unfortunately the regex looks pretty overloaded and scenario when there is an abbreviation in the beginning of the title is still not supported.

I need to fix this before merging the PR

**Comment by sergeyshushlyapin** [comment]
Hi @dirkrombauts,
I'm delaying with the fix for this one, but I'd appreciate to see #196 released as v1.0.2 ;)
Thanks!

**Comment by sergeyshushlyapin** [comment]
Done.

Implemented the following scenarios (the tests are in the `\src\pickles\pickles.basedhtmlfiles\tests\tests.js` file):

```javascript
equal(addSpacesToCamelCasedString("ThisIsATestStringABC"), "This Is A Test String ABC", "String with abbreviation at the end");
equal(addSpacesToCamelCasedString("ThisIsATestStringABC."), "This Is A Test String ABC.", "String with abbreviation and punctuation");
equal(addSpacesToCamelCasedString("ABCThisIsATestString"), "ABC This Is A Test String", "String with abbreviation at the beginning");
```

You're welcome to merge it.

**Comment by dirkrombauts** [comment]
Great, so we can include it in the next release after all :-)  I think #196 merits version v1.1.0 though ;-)

However: the DHTML version wasn't created by me, so I don't really know my way around it. I love unit test, but I don't really know how to run the tests.js tests - could you give me some hints on how to do that? I would ask the person who did most of the work on the DHTML version but he seems to have moved on.

**Comment by mkeCharlie** [comment]
I might be able to help with that version.

**Comment by dirkrombauts** [comment]
@mkeCharlie do you mean you will be able to help with explaining me how to run those unit tests (that would be cool) or with the DHTML version in general (that would be awesome)?

**Comment by mkeCharlie** [comment]
I think both, plus I work with the guy who implemented it in the first
place. :)

**Comment by dirkrombauts** [comment]
Cool. Say hello to Aaron for me ;-)

So how do I run those tests?

**Comment by sergeyshushlyapin** [comment]
Just open the page in a browser.

**Comment by dirkrombauts** [comment]
Excellent. I merged the pull request, and will publish a release soon.

Is there a way to run those tests as part of a continuous integration process?

**Pull request merged**
