### PR TITLE
Enhancement to support Unix path!

### PR DESCRIPTION
**Pull request by jboffel**
I'm not sure you already got a try or a feedback about it but actually pickles run relatively well under Linux with mono which is interesting when like me you can't get a windows machine.

However without this little change we can't get the folder structure display correctly.

Could you integrate this modification?

Thanks

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Hi,
Thanks for the feedback about Mono. I know that in theory it should be possible but I've never done it myself. Would you be willing to tell me a bit more about how Pickles on Mono? If so, please send me an email at dirk dot rombauts at picklesdoc dot com.

About the modification: I'll be glad to integrate this, but I have two questions:

1. In `splitDirectoryPathIntoArrayOfFormattedFolders` you use a regular expression, but in `folderHasSubdirectory` you use two separate statements. I'm neither a regex expert nor a javascript one, so could you educate me on your reasons?
2. Do we perhaps need a similar change in the other output formats?

**Comment by jboffel** [comment]
About the js modification, I always try to save the number of function call and the regexp let me check for as many path delimiter as i wish. It then even work for potential weird composite path that may happen from time to time like c:\\some/thing
For indexOf I use two separate call as unfortunately it does not support regexp...

**Comment by dirkrombauts** [comment]
I just tried this out on my mac ... the features in the directories are shown, but the directories themselves are not shown - like in the image:
screen shot 2016-05-13 at 20 22 06

Does it look like that on Linux too?

**Comment by jboffel** [comment]
Before my fix and if the json file was generated on Linux system through
mono yes it was like that.

With my fix now if generated on Linux with mono it has the directory.
However the image is not well created then you get those weird out looking
for your icons like next of links in the nav menu.

If despite my fix it does not works well on Mac I'll try to have a look on
mine.

Regards

**Comment by dirkrombauts** [comment]
Ah, yes, silly me - I was testing the latest released version. That doesn't include your change yet. I'll try again with the latest development version soon.

**Comment by dirkrombauts** [comment]
I tested the correct version now :-) The directories are shown, and there are indeed problems with the images as you pointed out.
One thing is weird, though: the highest level folder is called ".." instead of "Features" - both in the tree on the left side and in the links to the individual features. A look at the generated `pickledFeatures.js` reveals that the same is the case there. So it's not caused by your changes in the heirarchyBuilder.js file, but rather by something in Pickles. Does the same happen on Linux?

screen shot 2016-05-14 at 18 43 40

**Comment by jboffel** [comment]
Well yes and no, it seems it depends on mono version. Old one for unknown
reason will make pickles create a path with ..
But last one on recent Ubuntu seems to not prepend those two ..
So I'd bet Mac mono version is an old one.

Regards

**Comment by dirkrombauts** [comment]
I have Mono Mac v 4.2.3.4 which should be the latest version. *sigh*

Could you please post a screenshot of the result on Linux with the latest and greatest mono? I would like to see the result but I don't fancy setting up a Linux VM just for that :-(

**Comment by dirkrombauts** [comment]
Released in version [2.6.3](https://github.com/picklesdoc/pickles/releases/tag/v2.6.3).

**Pull request merged**
