### PR TITLE
no more stop on first malformed feature file. In case of parsing error then continue login error and at the final end return with failed status.

### PR DESCRIPTION
**Pull request by pleveill**

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks for the pull request. It's a starting point, but I don't consider it mergeable yet. For one thing, there are no tests.

But a more fundamental problem is this: your approach works only as long as there is a single FeatureParser instance. As soon as there are multiple ones, your approach breaks down. The FeatureParser is now responsible for parsing features *and* for keeping track of problems while parsing - the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle) tells us that that is not a good thing.

While researching how I would like you to approach the problem, I also found that there are a couple of other sources of problems with input files: the `Create` method of the `FeatureNodeFactory` class handles not only feature files but also markdown and image files.

How do you suggest we continue here? Do you have the time to work further on this?

**Comment by pleveill** [comment]
Yes I have time, for sure enough,  but not infinite of cause.

I have asked to myself the same question. There is not any kind of global status … variable/class anywhere in this design. Then I have used the FeatureParser adding a property in it, but yes the app design is prepared to make it pluggable with different implementations. At another side, you retrieve pluggable object using the class and not the interface. Then it is not as pluggable that it seems.

From this status I not know what is the best design, to put elsewhere this status and other things of the same kind. I hope you have a proposal ?

For tests, I will works on it …

De : Dirk Rombauts [mailto:notifications@github.com]
Envoyé : jeudi 9 mars 2017 11:59
À : picklesdoc/pickles <pickles@noreply.github.com>
Cc : Leveille, Pascal (Nokia - FR) <pascal.leveille@nokia.com>; Author <author@noreply.github.com>
Objet : Re: [picklesdoc/pickles] no more stop on first malformed feature file. In case of parsing error then continue login error and at the final end return with failed status. (#443)


Thanks for the pull request. It's a starting point, but I don't consider it mergeable yet. For one thing, there are no tests.

But a more fundamental problem is this: your approach works only as long as there is a single FeatureParser instance. As soon as there are multiple ones, your approach breaks down. The FeatureParser is now responsible for parsing features and for keeping track of problems while parsing - the Single Responsibility Principle<https://en.wikipedia.org/wiki/Single_responsibility_principle> tells us that that is not a good thing.

While researching how I would like you to approach the problem, I also found that there are a couple of other sources of problems with input files: the Create method of the FeatureNodeFactory class handles not only feature files but also markdown and image files.

How do you suggest we continue here? Do you have the time to work further on this?

**Comment by pleveill** [comment]
I have forget this :
My proposal is to use events. The bad thinks is that it need an event engine. I not know if the one used into wpf app is also available for not gui apps.

De : Leveille, Pascal (Nokia - FR)
Envoyé : jeudi 9 mars 2017 12:34
À : 'picklesdoc/pickles' <reply@reply.github.com>
Objet : RE: [picklesdoc/pickles] no more stop on first malformed feature file. In case of parsing error then continue login error and at the final end return with failed status. (#443)

Yes I have time, for sure enough,  but not infinite of cause.

I have asked to myself the same question. There is not any kind of global status … variable/class anywhere in this design. Then I have used the FeatureParser adding a property in it, but yes the app design is prepared to make it pluggable with different implementations. At another side, you retrieve pluggable object using the class and not the interface. Then it is not as pluggable that it seems.

From this status I not know what is the best design, to put elsewhere this status and other things of the same kind. I hope you have a proposal ?

For tests, I will works on it …

De : Dirk Rombauts [mailto:notifications@github.com]
Envoyé : jeudi 9 mars 2017 11:59
À : picklesdoc/pickles <pickles@noreply.github.com<mailto:pickles@noreply.github.com>>
Cc : Leveille, Pascal (Nokia - FR) <pascal.leveille@nokia.com<mailto:pascal.leveille@nokia.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [picklesdoc/pickles] no more stop on first malformed feature file. In case of parsing error then continue login error and at the final end return with failed status. (#443)


Thanks for the pull request. It's a starting point, but I don't consider it mergeable yet. For one thing, there are no tests.

But a more fundamental problem is this: your approach works only as long as there is a single FeatureParser instance. As soon as there are multiple ones, your approach breaks down. The FeatureParser is now responsible for parsing features and for keeping track of problems while parsing - the Single Responsibility Principle<https://en.wikipedia.org/wiki/Single_responsibility_principle> tells us that that is not a good thing.

While researching how I would like you to approach the problem, I also found that there are a couple of other sources of problems with input files: the Create method of the FeatureNodeFactory class handles not only feature files but also markdown and image files.

How do you suggest we continue here? Do you have the time to work further on this?

**Comment by dirkrombauts** [comment]
Yeah, it's not as pluggable as it seems ;-)  I'm using a lot of autofac and such but I'm not using the full power of dependency injection.

I'm currently doing some prototyping on what I would like to see - it's turning into a bigger thing than I imagined - if I want to have it done cleanly.

I would like to avoid using events so there'll be some kind of "exception report" object that collects the exceptions.

I can't fully tell you what I want to have for the error collection so any work you put in there is likely wasted. For that reason, I suggest that you work on the ExcludeTags property (using ` OR ` instead of `;` as separator) for the time being.

**Comment by dirkrombauts** [comment]
I did some prototyping and came up with a concept I'm more or less happy with. Would you be willing to give it a try and see if it addresses your need? You can find it at [my fork of the repository, in the parsing-report branch](https://github.com/dirkrombauts/pickles/tree/parsing-report).

**Comment by pleveill** [comment]
Yes it is ok, it is address my needs.
I see you have also added unit test on parsing error !
I like parsing report check into Runner that transform it into an exception.

The only point I have is the parsing error than only display at the end, all at the same time. I would prefer something that display them progressively (passing 1000 or 10000 feature take time).



De : Dirk Rombauts [mailto:notifications@github.com]
Envoyé : jeudi 9 mars 2017 14:35
À : picklesdoc/pickles <pickles@noreply.github.com>
Cc : Leveille, Pascal (Nokia - FR) <pascal.leveille@nokia.com>; Author <author@noreply.github.com>
Objet : Re: [picklesdoc/pickles] no more stop on first malformed feature file. In case of parsing error then continue login error and at the final end return with failed status. (#443)


I did some prototyping and came up with a concept I'm more or less happy with. Would you be willing to give it a try and see if it addresses your need? You can find it at my fork of the repository, in the parsing-report branch<https://github.com/dirkrombauts/pickles/tree/parsing-report>.

**Comment by dirkrombauts** [comment]
What I could do is log the information as it becomes available. I'll update that asap.

**Comment by dirkrombauts** [comment]
I pushed a new version - if you OK this soon, I'll release a new version of Pickles today!

**Comment by pleveill** [comment]
Thanks

De : Dirk Rombauts [mailto:notifications@github.com]
Envoyé : jeudi 9 mars 2017 15:56
À : picklesdoc/pickles <pickles@noreply.github.com>
Cc : Leveille, Pascal (Nokia - FR) <pascal.leveille@nokia.com>; Author <author@noreply.github.com>
Objet : Re: [picklesdoc/pickles] no more stop on first malformed feature file. In case of parsing error then continue login error and at the final end return with failed status. (#443)


I pushed a new version - if you OK this soon, I'll release a new version of Pickles today!

**Comment by dirkrombauts** [comment]
I'm closing this pull request since the relevant behavior is implemented in #445

**Comment by dirkrombauts** [comment]
@pleveill, I released the functionality in version [2.15.0](https://github.com/picklesdoc/pickles/releases/tag/v2.15.0). Thanks for your input in making this happen!

**Pull request closed without merging**
