### PR TITLE
Scenario Outline special characters workaround.

### PR DESCRIPTION
**Pull request by DominikBaran**
@dirkrombauts

### CODE REVIEW

**Comment by dirkrombauts** [comment]
I may have mentioned in another pull request that my regex skills are rusty :-)

What problem does this pull request solve? Could you perhaps create a unit tests that shows the problem?

**Comment by dirkrombauts** [comment]
Isn't this pull request very similar to #506 ? You closed #506, probably because you said "source tree did something really strange during the merge". 

I stand by the comment I made in #506 : If there is a bug, I want a unit test that shows the bug is solved. If you need assistance in creating a good unit test, please let me know.

**Comment by DominikBaran** [comment]
@dirkrombauts : 
1. Yes this change is an addition to #506. In the previous PR I fixed only white spaces in the Scenario Outline names - what is good and works perfectly fine. Then I realized there is also issue with special characters
ex: Scenario Outline: Support different users (admin/standard/new) 

2. I fixed special characters in the way:
2.1 in the ScenarioOutlineExampleIsMatch method for the scenario outline with special characters
exampleElement.name value is: support different users (admin/standard/new) - spaces and special characters
exampleElement.method value is: supportdifferentusersadminstandardnew -no spaces and special characters

Additionally the list of the "example" attributes is there : \(example: 1\).

So what I try to do is:
1. keep the previous matching functionality: 
return signature.IsMatch(exampleElement.name.ToLowerInvariant())

2. if we cannot match the name easily try to match the name without white spaces and special characters: 
signature.IsMatch(scenariotNameWithNoSpacesAndSpecialCharacters.ToLowerInvariant())

**Comment by DominikBaran** [comment]
@dirkrombauts : Hi Dirk. do you think you could help me with these unit tests ? Unfortunately I do not have any chance to update it in the reasonable time :(
Thanks

**Comment by dirkrombauts** [comment]
Hi @DominikBaran I want to help you but I'm more or less in the same situation - I don't have the opportunity to invest a lot of time in this. I'm chipping away at it, an hour here, half an hour there. Progress is slow.

**Comment by DominikBaran** [comment]
@dirkrombauts : understand. that's all good - if you will be able to submit some code in the future it would be awesome. if not i will also try organize some time and add unit tests (but it could be even 2nd half of the year).
Cheers,

**Comment by dirkrombauts** [comment]
@DominikBaran could you please check whether this problem still exists in version [2.18.1](https://github.com/picklesdoc/pickles/releases/tag/v2.18.1)? There are some big changes to the name matching in the new version.

**Comment by DominikBaran** [comment]
hello @dirkrombauts : unfortunately still the same issue:
image

**Comment by DominikBaran** [comment]
@dirkrombauts : I have also one observation after update my Xunit from 2.1.0 to 2.3.0/2.3.1
For the newer version of Xunit Scenario Outline reports do not work at all:
image

**Comment by DominikBaran** [comment]
@dirkrombauts : I also added small fix for Xunit 1.2.0 and 1.3.x issue. For the matcher I remove \\ if this kind of encoding exists

**Comment by dirkrombauts** [comment]
Thank you for your contribution (and your patience)

**Comment by MichielBerkhof** [comment]
Hi Dirk, 

I wonder if this also solves the following cases im facing: 

Examples:
  | email                 | outcome     | explanation                     |
  | A@b@c@example.com     | not created | only one @ character is allowed |
  | @example.com          | not created | localpart can't be empty        |
  | abc@                  | not created | domain can't be empty           |
  | john..doe@example.com | not created | double dot before @             |

It wont properly handle @ signs.

**Comment by dirkrombauts** [comment]
Hi @MichielBerkhof,

Good question - could you compile the latest version and test it? I will try to create a new release next week before I leave on holiday.

**Comment by MichielBerkhof** [comment]
Hi @dirkrombauts,

Ive cloned the repo, built the dev branch, and executed the pickles.exe against the scenario's.

This resulted in the following outcome: 
[pickledFeatures.js.txt](https://github.com/picklesdoc/pickles/files/2184805/pickledFeatures.js.txt)

I can see the @ signs in the examples, but the was executed and wassuccesfull both return false. Which makes me think it doesnt work yet?

Please let me know if i read this correctly

**Comment by MichielBerkhof** [comment]
Here's another add: 

The -1 scenario still doesnt seem to work for us. It runs correctly in VS2017 but pickles doesnt recognize it as being run and valid:

The feature file information
rate | explanation
-----|------------
0 | exchange rate can't be 0
-1 | exchange rate can't be negative
99.9999999 | exchange rate can't have more than six digits in the fractional part
99999999.99 | exchange rate can't have more than 7 digits in the integer part

The json pickles generates:
image

Here is the living documentation that it has resulted in:
image

**Comment by MichielBerkhof** [comment]
Hi @dirkrombauts,

Did you get a chance to look into these issues?

**Comment by dirkrombauts** [comment]
No, I'm sorry. I'm rather limited with my time. It would be helpful if you could provide me with .trx and .feature files - maybe I will be able to squeeze in some debugging time next week. Trying to get a release out of the door has priority though. There's some features that are waiting to see the official light of day.

**Comment by MichielBerkhof** [comment]
[CreateUsers.zip](https://github.com/picklesdoc/pickles/files/2196943/CreateUsers.zip)

Hi @dirkrombauts,

Above ZIP contains our CreateUser scenario with the trx results generated by TeamCity. In these examples you can see the scenario: Can't create user with invalid email address

In the trx, they all pass, but pickles wont see them as passed. I hope you could squeeze in just a little extra effort, would be much appreciated by our PO ;)

**Comment by dirkrombauts** [comment]
Hi @MichielBerkhof 

The reality of an open source project is that the fastest way to get something done is to fix it yourself and then send a pull request :-)

Cheers,
Dirk

**Comment by dirkrombauts** [comment]
Released in version [2.19.0](https://github.com/picklesdoc/pickles/releases/tag/v2.19.0)

**Comment by dirkrombauts** [comment]
@MichielBerkhof I created a new issue to track the problems with @ signs and such that you reported on 11 July.

**Comment by MichielBerkhof** [comment]
Thanks dirk, ill try to find some spare time at work to take a more detailed look into it, but cant promise i can find the time. Its kinda busy...

**Pull request merged**
