### PR TITLE
Cucumber w/ Tests

### PR DESCRIPTION
**Pull request by armsteadj1**
Updated the cucumber pull request to include tests and remove regions.

Tested against XRay and it works well.

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks for you contribution. It seems there are some tests failing, could you please look into that?

**Comment by armsteadj1** [comment]
Huh, odd. I'll try and track this down locally, I haven't been able to reproduce it yet.

**Comment by dirkrombauts** [comment]
Superseded by #413

**Comment by dirkrombauts** [comment]
Released in version [2.12.0](https://github.com/picklesdoc/pickles/releases/tag/v2.12.0). Thanks for your contribution in September and thanks for your patience.

**Pull request closed without merging**
