### PR TITLE
Add Overview Dashboard to DHTML Pickles Site with Summary Charts by Namespace and Tags

### PR DESCRIPTION
**Pull request by ocsurfnut**
Creates an Overview / Dashboard screen for the Pickles DHTML site:

The charts on this page are sourced from a new `Summary` section in the `pickledFeatures.js` file which is generated during the compilation phase.  This PR includes a hard-coded implementation detail that is specific to one of our projects, the separation of `@NotTested` tags into their own chart.  The specification of any tags to process this way may be better done with a command-line parameter or config file, but time prevented us from taking it any further.

Hope this proves to be a useful feature!

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks, that picture certainly looks impressive!  Many thanks for your contribution.

I'm going to release a new version of Pickles tomorrow, but since I want to have a proper look at your contribution I will not include it yet.

In the meantime, could you perhaps explain the `@NotTested` tag thing a bit further? What problem are you solving with it?

Again, thanks for you work!

**Comment by ocsurfnut** [comment]
Hi @dirkrombauts , thanks!  We appreciate your team's hard work on Pickles, and we love the "living documentation" the DHTML site affords.

Our team uses the `@NotTested` tag on scenarios (or sometimes entire features) that we intentionally are not hooking up tests for.  This allows the stakeholders to opt out of testing certain scenarios when time does not permit or when the scenario is not deemed critical enough to have accompanying tests.  As advocates for BDD, we don't really like this, but its the reality of how our projects are run.  Having a seperate chart to show how many times this tag has been used raises the awareness of what we are not testing and helps us identify if that option may be getting abused a bit.

We could easily add in some logic that If the `@NotTested` tag is never used, the chart will never appear.  As we have more time, we were thinking a config file would be the best option, as we could use this to define other "buckets" for reporting based on Tags and Test Result (ex.  `@ToBeImplemented` + Failing = Pending BDD`).

**Comment by jamiesmy** [comment]
We could also add an optional parameter to specify one tag that gets the namespace breakdown.

**Comment by dirkrombauts** [comment]
A quick update ... I haven't forgotten about this ;-)

I am not entirely sure I want the report exactly like this, but on the other hand I don't want to hold this code back while I sit and make up my mind. There are one or two other things in a similar state of limbo.

For that reason, I have decided to introduce "experimental features" that people can opt in to, and will (hopefully) give feedback about. I'm busy setting up the infrastructure, and I hope I will be able to release it all on Friday 11 March.

Thanks for your patience!

**Comment by ocsurfnut** [comment]
Sounds good @dirkrombauts, I like the idea!

Don't feel like you have to rush on our behalf, we're using a version with the Overview page internally while we await your changes.

Thanks!

**Comment by dirkrombauts** [comment]
Real life intervening ... the infrastructure for experimental features is now in place.

However, I had to make changes that mean your branch is now in conflict with the main branch. Could you do me a favour and fix those conflicts on your branch?

**Comment by dirkrombauts** [comment]
I'm having a go at fixing the merge issues myself. I hope to release this tomorrow!

**Comment by dirkrombauts** [comment]
Released in version [2.5.0](https://github.com/picklesdoc/pickles/releases/tag/v2.5.0).

**Comment by dirkrombauts** [comment]
Please post further comments in #306

**Comment by ocsurfnut** [comment]
Thanks @dirkrombauts , been a busy few days!  I'll implement Pickles 2.5.0 and let you know how it goes.

**Pull request merged**
