### PR TITLE
Add FilterTags feature

### PR DESCRIPTION
**Pull request by spacehole1**
Hello,

My Proposition for issue #527 
I still need to add several Unit test to check : feature generated with all or only filtered elements

Regards,

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks for your contribution. I haven't looked at in detail yet, because I got stuck at the name "FilterTags". To me, "filter" sounds like "filter out" - and the tag actually does the opposite thing. How about something like "IncludeOnlyTags"?

**Comment by dirkrombauts** [comment]
So far so good ... but there's a conflict (your other changes to the MSBuild.targets file) and I see no changes to the .xaml file for the GUI. Could you add those please? Then we're good to go.

**Comment by spacehole1** [comment]
Good idea. I changed my code to take your remark in account

**Comment by spacehole1** [comment]
Thanks for the remark, I always miss the UserInterface..

**Comment by dirkrombauts** [comment]
Cool, thanks!

I noticed another thing that's missing: there are no unit tests ... could you please add some?

**Comment by flubbid** [comment]
Was this ever implemented?

**Comment by dirkrombauts** [comment]
Hi,

Thank you for your contribution, and the time you put into this.

Unfortunately, the feature does not work as advertised. I found two problems:

- separating multiple tags by semicolon does not work
- A directory that included no scenarios or features that were tagged to be included, was included anyway as an empty directory.

I'm in the process of ending my involvement in Pickles. I don't have the time or energy to investigate these issues, so I'm closing the pull request and will not include it.

Thanks again for the time you put into this.

**Pull request closed without merging**
