### PR TITLE
For works with Edge, Firefox, ...

### PR DESCRIPTION
**Pull request by swoog**

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thank you for your contribution!

Could you please explain a bit - which problem are you solving with this change?

Thanks again!

**Comment by swoog** [comment]
The bug on Firefox, Edge, ... is the table is size to 0px and the column are force to the minimu value. So the texte when is sentences is more difficult to read. If you see your table on [http://www.picklesdoc.com/Output/DHtml/Index.html#Features\05TablesAndAssist\TableScenario.feature] The Birth date is on two lines.

**Comment by dirkrombauts** [comment]
I will play around with it a bit. I have had lots of complaints about the tables. Some people say they are too wide, some say they are too small, ... I will experiment with your solution and compare it to the stylesheet of the static html version.

**Comment by dirkrombauts** [comment]
Thank you for your contribution!

**Pull request merged**
