### PR TITLE
Fixed defect in MSTestElementExtensions...

### PR DESCRIPTION
**Pull request by aaronjrich**
...where a carriage return in xml l value tag should have been trimmed in order to compare to empty string.  This was causing pickle to fail for files that contain this issue.

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks for this PR. I wonder if the same problem is lurking in the other test result providers. Would you have time to investigate that?

**Comment by aaronjrich** [comment]
I can't commit to when I can get at this as I spent more time than I thought I was going to, to prove I've made the fix.  This issue is affecting a team that was updating to a newer version of pickles.  I pinpointed what was happening by debugging against their file.  The hardest thing to do was to make a test the proved it wasn't working with a sample test results file that I manufactured.  I'm not sure I can do the same for the other test provider given I'm not familiar with many of them but I can try to take a look when I get some free time.

**Comment by dirkrombauts** [comment]
I understand. In case I want to investigate: what should I pay attention to? What makes the sample test results file special? How do I provoke the bug?

**Comment by aaronjrich** [comment]
When you have blank examples entries in a scenario outline, and MSTest 2015 version (I think), it will emit xml like so:
```
<value>
</value>
```

rather than: 
`<value></value>`

So what was happening was the value was a carriage return rather than a blank value so it would not match up to the parse scenario outline data.

That's about all I know about this issue.  I literally put in a Trim() and it fixed it (see the change to src/Pickles/Pickles.TestFrameworks/MsTest/MsTestElementExtensions.cs).  We also use NUnit2 & 3 and latest version of Pickles and haven't seen this issue yet.

**Comment by dirkrombauts** [comment]
Thanks for the information!

I will leave this PR open for now as a reminder to myself to have a look at this. If neither of us gets around to investigating it closer by the end of next week, I will merge it.

**Comment by dirkrombauts** [comment]
Thanks again @aaronjrich

**Comment by dirkrombauts** [comment]
Released in version [2.8.1](https://github.com/picklesdoc/pickles/releases/tag/v2.8.1)

**Pull request merged**
