### PR TITLE
Adding Cucumber JSON as possible export format

### PR DESCRIPTION
**Pull request by jgrossrieder**
I added the cucumber's JSON output format, as it is used for several tools as standard input test result.
This is related to the  #278

### CODE REVIEW

**Comment by dirkrombauts** [comment]
I did a quick review of the code. It looks plausible, but I am missing unit tests. I follow a strict test-driven approach in Pickles, so I need unit tests to go with the production code.

And a minor code style detail: do me a favour and remove the #regions :-)

The code itself looks elegant - is Cucumber JSON really that simple a format? I am no expert on Cucumber ...

**Comment by jgrossrieder** [comment]
Sorry, I already spent way more time that I was allowed on this.
(I love region ;) )

I'm far from being a cucumber expert(nor specflow), so I can just say that this is accepted as valid input within XRAY, as a cucumber output file.

**Comment by dirkrombauts** [comment]
I understand - I will leave the PR open for the moment because it's a useful feature. Maybe someone will come along and add the unit tests :-)

**Comment by dirkrombauts** [comment]
Superseded by #413

**Comment by dirkrombauts** [comment]
Released in version [2.12.0](https://github.com/picklesdoc/pickles/releases/tag/v2.12.0). Thanks for your contribution in July and for your patience.

**Pull request closed without merging**
