### PR TITLE
Pickles is unable to deal with Danish characters

### PR DESCRIPTION
**Pull request by s991116**
Test with danish character ('æ', 'ø', 'å') is not found in test results.
The mapping of scenario-steps with these charaters are not mapped (eg. æ => ae)
Only danish characters are added to the SpecflowNameMapping.

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks for this extension! Could you please provide unit tests as well? Thanks

**Comment by s991116** [comment]
I will try. What about the test harness? I don't have that up and running,
yet.

/Philip

**Comment by dirkrombauts** [comment]
The test harness is a separate solution in the same repository. You need to install a few non-standard components for that, I'm afraid. 

The [Contributing.md](https://github.com/picklesdoc/pickles/blob/develop/CONTRIBUTING.md) should contain the info you need to get started. If there's something missing or unclear, please let me know so I can adapt it.

**Comment by s991116** [comment]
I will give it a try.

**Comment by dirkrombauts** [comment]
Thanks for the update! I'll have a look soon and see whether I can do something about the Ruby and JS results. If I can, I'll add them to your pull request.

**Comment by s991116** [comment]
I'm not able to generate test-output for Cucumber (Ruby) and CucumberJS. The Json files are empty
I have added steps (MinimalSteps.js / MinimalSteps.rb), but I think it is not able to match the step-definition.

Regarding converting special characters, It could have been made more general, by using the converter from Specflow.  You can see the code used in SpecFlow [here](https://github.com/techtalk/SpecFlow/blob/master/TechTalk.SpecFlow/Tracing/CodeFormattingExtensions.cs)

**Comment by dirkrombauts** [comment]
I got the Cucumber Ruby results to work, and I added an entry to the change log. I had to merge changes from the upstream develop branch.

The Cucumber JS test results are a bit of a mystery still - they don't work at all (the ruby ones only didn't pick up the Danish stuff). I'll need to investigate that more.

**Comment by s991116** [comment]
Thanks for looking into it.
I hope to be able to use the test result with Danish specifications, to
have focus on test automation.

**Comment by s991116** [comment]
Hi
Do you have an estimate on when a release with this change will be available?

**Comment by dirkrombauts** [comment]
I hope to have something by the end of the week, but I can't guarantee anything. I can get the CucumberJS results to work with some manual editing, but I'd like to get to the bottom of it because otherwise the next time we change the test results we'll have the same issue.

**Comment by dirkrombauts** [comment]
Thanks for your contribution and patience. I hope to release a new version in the coming days, but you can compile your own from source in the meantime.

**Comment by dirkrombauts** [comment]
Released in version [2.16.2](https://github.com/picklesdoc/pickles/releases/tag/v2.16.2)

**Pull request merged**
