### PR TITLE
Changed types of aggregate stats to int instead of byte

### PR DESCRIPTION
**Pull request by eugene-sea**
Recently we have switched to xUnit.net from MSTest for SpecFlow. Immediately we have run into issue with pickles — it is failed due to XML load exception. The issue is with XSD schema: aggregate stats are defined as unsigned bytes. This means maximum number of tests are limited to 255 but we have much more.

I have updated schema so aggregates are now int. (pickles code assumes they have ```signed int``` type.)

There is no changes in code. Only schema and generated code are updated. It is difficult to create test for this issue as number of tests in results should be greater than 255.

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thank you for your contribution! I plan to release a new version by the end of the week.

**Comment by dirkrombauts** [comment]
Released in version [2.11.0](https://github.com/picklesdoc/pickles/releases/tag/v2.11.0).

**Comment by eugene-sea** [comment]
Thank you

**Comment by eugene-sea** [comment]
@dirkrombauts after I have updated CI to use 2.11.0 — builds are started to fail with the same issue as before ("number of tests is too big"). I have created custom build with this PR and it works. It looks like 2.11.0 does not contain this PR.

**Comment by dirkrombauts** [comment]
Maybe I made a mistake when merging ... I will look into it. Thanks for letting me know!

**Comment by dirkrombauts** [comment]
I see it now ... it was merged into the wrong branch. My apologies for the oversight.

**Comment by dirkrombauts** [comment]
I released a corrected version in version [2.11.1](https://github.com/picklesdoc/pickles/releases/tag/v2.11.1).

**Comment by eugene-sea** [comment]
Thank you

**Pull request merged**
