### PR TITLE
Compatibility with nunit.console 3.4 and nunit.framework 2.6

### PR DESCRIPTION
**Pull request by lars-erik**

### CODE REVIEW

**Comment by dirkrombauts** [comment]
Thanks. The code looks good. However, I am following a test-first policy on Pickles, so in order for me to merge this pull request, there need to be some unit tests. Do you think you could add those?

**Comment by lars-erik** [comment]
I added a test output matching nunit 2 tests ran with nunit 3 runner. (Tbh. I copied the nunit 3 output and renamed the description attribute names)
It fails without the change and passes with the change. Should be aye ok.

**Comment by dirkrombauts** [comment]
Thanks for the addition, i'll look into it tomorrow. If it checks out, I'll do a release next week.

**Comment by lars-erik** [comment]
Great.

On another note, it'd be nice to be able to plug in new generators. For instance feature and scenario names only to Excel. Is that something you'd pull if I can sew it together?

Vennlig hilsen

Lars-Erik Aabech
Faglig leder utvikling
MarkedsPartner AS
www.markedspartner.no
+47 920 30 537
________________________________

**Comment by dirkrombauts** [comment]
Yes, I am in favour of a plugin-like system for output formats (as long as it is test-driven ;-) ). This ties in nicely with something else I would like to do: move the output generators to their own project(s). One of the goals there is to make it easier to separate the .NET core-compatible output generators from those that aren't. Would you be interested in doing this refactoring as a prelude to your idea?

**Comment by lars-erik** [comment]
I'll give it a shot. Got quite a few balls in the air, so having difficulty committing, but pickles is one of my new favorite softwares, so it's high up in my todo stack. ;)  
I'll work off the existing tests and add as soon as I break the coverage.

**Comment by dirkrombauts** [comment]
Released in version [2.8.3](https://github.com/picklesdoc/pickles/releases/tag/v2.8.3)

**Comment by lars-erik** [comment]
\o/
back in project next week. thanks again for great collab.

**Pull request merged**
